# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true
  #footnote_backlink: "&#8617;&#65038;" # add variation selector 15 to force backarrow for footnotes to be rendered as text, not emoji (doesn't work for chrome?)
  footnote_backlink: "" # do not use backlink for footnotes

# Permalinks
permalink:      none

# Server
source:            "."
destination:    ./_gh_pages
host:               0.0.0.0
port:              9001
baseurl:         ""
url:                 "https://130.dingthemself.com"
encoding:       UTF-8
timezone:       America/Phoenix
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - nuget/
  - scss/
  - vendor/
  - CODE_OF_CONDUCT.md
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - sache.json
  - twbsconfig.yml

plugins:
  - jekyll-sitemap
  - jekyll-target-blank

sass:
    sass_dir: _sass
    style: compressed

# Course
institution:            "the University of Arizona"
institution_email_domain: "arizona.edu"
semester:              "Fall 2024"
course_number:  "Phil 130"
course_title:         "Sex, Gender, and Love"
course_title_full:  "Sex, Gender, and Love: An Introduction to Social Philosophy"
description:        "Course website for Phil 130: Sex, Gender, and Love at the University of Arizona"
instructor:            "Ding"
instructor_website: "https://dingherself.com"
instructor_netid:   "din"
office:                   "Social Sciences 138"
office_hours:       "Th 2:45–4:15pm, and by appointment"
meeting_time:     "TuTh 9:30–10:45am"
classroom:            "Harvill 305"
learning_site:       "https://d2l.arizona.edu/d2l/home/1453095"
ta_title: "Grader"
ta_name: "Ryan Hauger (he/him)"
ta_netid: "ryanellishauger"
ta_office: "TBD"
ta_office_hours: "By appointment"

# Custom variables
#current_version:      4.0.0
#current_ruby_version: 4.0.0
#docs_version:         4.0
#repo:                 "https://github.com/twbs/bootstrap"
#slack:                "https://bootstrap-slack.herokuapp.com"
#blog:                 "https://blog.getbootstrap.com"
#expo:                 "https://expo.getbootstrap.com"
#jobs:                 "https://jobs.getbootstrap.com"
#themes:               "https://themes.getbootstrap.com"

#download:
#  source:           "https://github.com/twbs/bootstrap/archive/v4.0.0.zip"
#  dist:             "https://github.com/twbs/bootstrap/releases/download/v4.0.0/bootstrap-4.0.0-dist.zip"

#cdn:
  # See https://www.srihash.org for info on how to generate the hashes
#  css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
#  css_hash:         "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
#  js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
#  js_hash:          "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
#  jquery:           "https://code.jquery.com/jquery-3.2.1.slim.min.js"
#  jquery_hash:      "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
#  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
#  popper_hash:      "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"